/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Edgar
 */
public class ViewRfc extends javax.swing.JFrame {

    /**
     * Creates new form VewRfc
     */
    public ViewRfc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_nombre = new javax.swing.JLabel();
        jl_paterno = new javax.swing.JLabel();
        jl_materno = new javax.swing.JLabel();
        jl_anio = new javax.swing.JLabel();
        jtf_nombre = new javax.swing.JTextField();
        jtf_paterno = new javax.swing.JTextField();
        jtf_materno = new javax.swing.JTextField();
        jtf_anio = new javax.swing.JTextField();
        jtf_mes = new javax.swing.JTextField();
        jl_mes = new javax.swing.JLabel();
        jtf_dia = new javax.swing.JTextField();
        jl_dia = new javax.swing.JLabel();
        jbtn_rfc = new javax.swing.JButton();
        jl_rfc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_nombre.setBackground(new java.awt.Color(0, 102, 102));
        jl_nombre.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jl_nombre.setText("Nombre:");

        jl_paterno.setBackground(new java.awt.Color(0, 102, 102));
        jl_paterno.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jl_paterno.setText("Apellido Paterno:");

        jl_materno.setBackground(new java.awt.Color(0, 102, 102));
        jl_materno.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jl_materno.setText("Apellido Materno:");

        jl_anio.setBackground(new java.awt.Color(0, 102, 102));
        jl_anio.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jl_anio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_anio.setText("Año");

        jtf_nombre.setBackground(new java.awt.Color(0, 102, 102));
        jtf_nombre.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jtf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nombreActionPerformed(evt);
            }
        });

        jtf_paterno.setBackground(new java.awt.Color(0, 102, 102));
        jtf_paterno.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N

        jtf_materno.setBackground(new java.awt.Color(0, 102, 102));
        jtf_materno.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N

        jtf_anio.setBackground(new java.awt.Color(0, 102, 102));
        jtf_anio.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N

        jtf_mes.setBackground(new java.awt.Color(0, 102, 102));
        jtf_mes.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N

        jl_mes.setBackground(new java.awt.Color(0, 102, 102));
        jl_mes.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jl_mes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_mes.setText("Mes");

        jtf_dia.setBackground(new java.awt.Color(0, 102, 102));
        jtf_dia.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N

        jl_dia.setBackground(new java.awt.Color(0, 102, 102));
        jl_dia.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jl_dia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_dia.setText("Dia");

        jbtn_rfc.setBackground(new java.awt.Color(0, 102, 102));
        jbtn_rfc.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jbtn_rfc.setText("RFC");
        jbtn_rfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_rfcActionPerformed(evt);
            }
        });

        jl_rfc.setBackground(new java.awt.Color(0, 102, 102));
        jl_rfc.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jl_rfc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_rfc.setText("RFC");

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel1.setText("RFC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn_rfc)
                        .addGap(9, 9, 9)
                        .addComponent(jl_rfc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jl_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jl_mes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 67, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jtf_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtf_mes))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jl_materno)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jl_nombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jl_paterno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtf_nombre)
                                            .addComponent(jtf_materno)
                                            .addComponent(jtf_paterno))))
                                .addGap(34, 34, 34)
                                .addComponent(jtf_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nombre)
                    .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_paterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_paterno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_materno)
                    .addComponent(jtf_materno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_anio)
                    .addComponent(jl_mes)
                    .addComponent(jl_dia))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_rfc)
                    .addComponent(jbtn_rfc))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_rfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_rfcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_rfcActionPerformed

    private void jtf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRfc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRfc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRfc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRfc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRfc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JButton jbtn_rfc;
    public javax.swing.JLabel jl_anio;
    public javax.swing.JLabel jl_dia;
    public javax.swing.JLabel jl_materno;
    public javax.swing.JLabel jl_mes;
    public javax.swing.JLabel jl_nombre;
    public javax.swing.JLabel jl_paterno;
    public javax.swing.JLabel jl_rfc;
    public javax.swing.JTextField jtf_anio;
    public javax.swing.JTextField jtf_dia;
    public javax.swing.JTextField jtf_materno;
    public javax.swing.JTextField jtf_mes;
    public javax.swing.JTextField jtf_nombre;
    public javax.swing.JTextField jtf_paterno;
    // End of variables declaration//GEN-END:variables
}
